"""Tests for the LLM-backed script writer agent."""

from __future__ import annotations

import pytest

from docuresearch.agents.script_agent import generate_script
from docuresearch.models.claims import Claim
from docuresearch.models.research import StoryArchitecture, StorySection
from tests.conftest import FakeChatModel

CANNED_SCRIPT = {
    "title_suggestions": ["Title A", "Title B"],
    "introduction": "Here is where it all began.",
    "sections": [
        {"heading": "Origins", "narration": "It started here.", "cited_claim_ids": ["C-1", "C-999"]},
        {"heading": "Aftermath", "narration": "Then this happened.", "cited_claim_ids": ["C-2"]},
    ],
    "conclusion": "And that's the story.",
    "cta": "Subscribe for more.",
}


@pytest.mark.asyncio
async def test_generate_script_maps_llm_output() -> None:
    claims = [Claim(claim_id="C-1", text="Claim one.", confidence=0.9), Claim(claim_id="C-2", text="Claim two.", confidence=0.8)]
    fake_model = FakeChatModel(CANNED_SCRIPT)

    draft = await generate_script(
        "Test Topic",
        language="english",
        tone="urgent",
        script_length="10min",
        target_audience="general audience",
        story_architecture=None,
        claims=claims,
        hook_text="This is the hook.",
        version=1,
        model_name="gpt-4o-mini",
        model=fake_model,
    )

    assert draft.hook_text == "This is the hook."  # never regenerated by the LLM
    assert draft.title_suggestions == ["Title A", "Title B"]
    assert draft.introduction == "Here is where it all began."
    assert len(draft.sections) == 2
    assert draft.conclusion == "And that's the story."
    assert draft.cta == "Subscribe for more."
    assert draft.version == 1
    assert draft.model_name == "gpt-4o-mini"
    assert "This is the hook." in draft.full_text


@pytest.mark.asyncio
async def test_generate_script_drops_invented_claim_ids() -> None:
    claims = [Claim(claim_id="C-1", text="Claim one.", confidence=0.9), Claim(claim_id="C-2", text="Claim two.")]
    fake_model = FakeChatModel(CANNED_SCRIPT)

    draft = await generate_script(
        "Test Topic",
        language="english",
        tone=None,
        script_length="10min",
        target_audience="general audience",
        story_architecture=None,
        claims=claims,
        hook_text="Hook.",
        model=fake_model,
    )

    # C-999 was never a real claim id - must be dropped, not trusted.
    assert draft.sections[0].cited_claim_ids == ["C-1"]
    assert draft.sections[1].cited_claim_ids == ["C-2"]


@pytest.mark.asyncio
async def test_generate_script_accepts_story_architecture_and_feedback() -> None:
    """Just confirms these optional params flow through without error - a fake model
    ignores prompt content, so this checks plumbing, not prompt wording."""
    architecture = StoryArchitecture(
        central_question="Why?", sections=[StorySection(id="SEC-1", name="Origins", purpose="p", key_claim_ids=["C-1"])]
    )
    claims = [Claim(claim_id="C-1", text="Claim one.", confidence=0.9)]
    fake_model = FakeChatModel(CANNED_SCRIPT)

    draft = await generate_script(
        "Test Topic",
        language="hinglish",
        tone="casual",
        script_length="5min",
        target_audience="young adults",
        story_architecture=architecture,
        claims=claims,
        hook_text="Hook.",
        feedback=["Fix the exaggeration in section 2."],
        version=2,
        model=fake_model,
    )
    assert draft.version == 2
